[Interface]
PrivateKey = # Fill key
Address = 10.0.0.X/24 # Fill last digit
DNS = 172.16.16.14
MTU = 1420

[Peer]
PublicKey = ZI6JFI1H/a5jh15fpQa88JqhDYaljryGsZdDxjefqzc=
AllowedIPs = 10.0.0.0/24, 172.16.16.0/24
Endpoint = 195.154.212.150:51820
PersistentKeepalive = 25